# // opcode table //
optable = {
    'nop'   : 0,
    'mov'   : 1,
    'add'   : 2,
    'sub'   : 3,
    'beq'   : 4,
    'bne'   : 5,
    'blt'   : 6,
    'bgt'   : 7,
    'jmp'   : 8,
    'jal'   : 9,
    'jr'    : 10,
    'load'  : 11,
    'stor'  : 12,
    'sysc'  : 13,
    # alternate imms
    'movi'  : 14,
    'addi'  : 15,
    'subi'  : 16,
    'loadi' : 17,
    'stori' : 18
}
op_lookup = {
    0	: 'nop',
	1	: 'mov',
	2	: 'add',
	3	: 'sub',
	4	: 'beq',
	5	: 'bne',
	6	: 'blt',
	7	: 'bgt',
	8	: 'jmp',
	9	: 'jal',
	10	: 'jr',
	11	: 'load',
	12	: 'stor',
	13	: 'sysc',
    # alternate imms
	14	: 'movi',
	15	: 'addi',
	16	: 'subi',
	17	: 'loadi',
	18	: 'stori'
}
# // register table //
regtable = {
    '$nil'  : 0,
    '$t0'   : 1,
    '$t1'   : 2,
    '$mp'   : 3,
    '$a0'   : 4,
    '$a1'   : 5,
    '$a2'   : 6,
    '$s0'   : 7,
    '$s1'   : 8,
    '$vc'   : 9,
    '$sp'   : 10,
    '$ra'   : 11
}